### ISSUE TITLE
.csv files are not CSV format

### ISSUE THREAD

**Issue by pwalsh** [gvidon/uk-expenditure#1]
Hello @gvidon (I'm following up here on behalf of Open Knowledge)

One this here is that the .csv files in data/\* are not actually CSV, they are TSV.

**Comment by gvidon** [comment]
@pwalsh yes, I know they all have `\t` as a delimeter. Currently all scripts output rows as:
`Some value<CSV_DELIMETER>another one<CSV_DELIMETER>and the last one`

I will change it to
`"Some value"<CSV_DELIMETER>"another one"<CSV_DELIMETER>"and the last one"`

And use `,` as `CSV_DELIMETER`. You can later change `CSV_DELIMETER` in `settings.py` to any value.

**Comment by pwalsh** [comment]
Why not use Python's csv module for this, rather than constructing the rows yourself? That would ensure you get proper delimiting, quoting, etc.

**Comment by gvidon** [comment]
I don't want to overload the app with extra dependencies when need simple solution.

**Comment by pwalsh** [comment]
it is not an extra dependency - it is built into python. Writing your own is too prone to breakage. 

Example: a field that uses " or , as a valid character in it.

**Comment by gvidon** [comment]
Yes, I know that it is system package.

**Comment by pwalsh** [comment]
in any event, both the current solution, and a solution where you "manually" quote every single field with " chars will break in many commons cases, as I wrote above. In terms of lines of code, it would be pretty equivalent.

CSV output is really critical for us; TSV is not really used.

**Comment by gvidon** [comment]
Ok, I will use `csv`.

**Comment by gvidon** [comment]
@pwalsh updated all scripts to use system `csv`. CSV files were emptied during tests, need to run scripts to fill them up.

**Comment by gvidon** [comment]
@pwalsh other issues will be fixed later today

**Comment by pwalsh** [comment]
Awesome. Thanks @gvidon.
