### ISSUE TITLE
[meta] Overall Process

### ISSUE THREAD

**Issue by rufuspollock** [gvidon/uk-expenditure#14]
**Scrape the list of files - this is the "data" for this repo**
1. Get list of publishers
2. Get list of all datafiles

**Analyse data**
1. cache datafiles
2. run validation / check
3. generate summary results
## Asides
- Should we write to sqlite and then dump to csv as needed? Could be quite nice as a process and actually what you want?

**Comment by pwalsh** [comment]
The overall process is described in detail in the README. I'm not too happy with the current process as we are not using sod-admin to its full potential, but that is another issue https://github.com/okfn/uk-expenditure-files/issues/15
