### ISSUE TITLE
Make this repository a valid Data Package

### ISSUE THREAD

**Issue by pwalsh** [gvidon/uk-expenditure#17]
Make this repository a valid [Data Package](http://dataprotocols.org/data-packages/), `datapackage.json`, with a `resources` array for the stuff in `data`, and use the `sources` array for the stuff in `fetched`

**Comment by georgiana-b** [comment]
Does this imply that the whole process should work for this [option in GoodTables](https://github.com/frictionlessdata/goodtables/blob/478cfe2beb5f8d7a811c4afe7ee50820331e64ce/goodtables/pipeline/batch.py#L86)?

**Comment by pwalsh** [comment]
Done
