### ISSUE TITLE
Add sources from gov.uk

### ISSUE THREAD

**Issue by pwalsh** [gvidon/uk-expenditure#18]
Copied out of #15 as looks like this needs special treatment.

 @jacattell @davidread if you can tell me who can actually provide any clarity on this for those outside of government that would be great!

Useful reference, perhaps:
- https://twitter.com/jukesie/status/717754873278828544
- https://twitter.com/RiversBenG/status/722168666448666624
- https://twitter.com/owenboswarva/status/721058394711408641
- https://www.gov.uk/government/publications/cabinet-office-spend-data

It looks like gov.uk is listing datasets that have not been pushed to data.gov.uk. 

Example query (https://www.gov.uk/government/publications?keywords=spend&publication_filter_option=transparency-data&topics%5B%5D=all&departments%5B%5D=all&official_document_status=all&world_locations%5B%5D=all&from_date=&to_date=). 

<strike>As far as I know, we are supposed to be assessing data.gov.uk, being the data portal of the UK govt., so I'm not 100% sure we should look for data on this location too.</strike>

Looks like we really should query against gov.uk too.

**Comment by pwalsh** [comment]
@georgiana-b 

As a first pass, try:
- Write some queries against gov.uk to get the data we are searching for
- Filter out data we already have from data.gov.uk
- Add a new column to `sources.csv` to identify the publication platform: `data.gov.uk` or `gov.uk`

**Comment by georgiana-b** [comment]
According to this [issue I opened](https://github.com/alphagov/rummager/issues/631) sources from [gov.uk](https://www.gov.uk) will have to be scraped from HTML. From experiments and deduction I think we already have these files for the publishers we requested from [data.gov.uk](https://data.gov.uk), but until we scrape them and compare or somebody clarifies the matter, we can't know for sure. I'll give it a few days.

**Comment by georgiana-b** [comment]
The results returned by [a query to  gov.uk api ](http://www.gov.uk/api/search.json?q=25k&&filter_display_type=Transparency data&filter_organisations[]=attorney-generals-office&filter_organisations[]=cabinet-office&filter_organisations[]=department-for-business-innovation-and-skills&filter_organisations[]=department-for-communities-and-local-government&filter_organisations[]=department-for-culture-media-and-sport&filter_organisations[]=department-for-education&filter_organisations[]=department-for-environment-food-and-rural-affairs&filter_organisations[]=department-for-international-development&filter_organisations[]=department-for-transport&filter_organisations[]=department-for-work-and-pensions&filter_organisations[]=department-of-energy-and-climate-change&filter_organisations[]=department-of-health&filter_organisations[]=foreign-and-commonwealth-office&filter_organisations[]=hm-treasury&filter_organisations[]=home-office&filter_organisations[]=ministry-of-defence&filter_organisations[]=ministry-of-justice&filter_organisations[]=northern-ireland-office&filter_organisations[]=office-of-the-advocate-general-for-scotland&filter_organisations[]=scotland-office&filter_organisations[]=uk-export-finance&filter_organisations[]=wales-office) contain only links to HTML pages. This means that  none of them is in an open format. Should I scrape the links to the CSV and XLS files from those  HTML pages?

**Comment by pwalsh** [comment]
Hi. In that case - no. It is a real problem for publication if we actually need to scrape html to find the published data. You do not need to proceed on this issue, but I'll leave it open for the moment anyway.

**Comment by pwalsh** [comment]
WONTFIX.
