### ISSUE TITLE
Data file title format

### ISSUE THREAD

**Issue by pwalsh** [gvidon/uk-expenditure#2]
the title column in the datafiles.tsv/csv output currently has a date string. Could the format please be:

 dataset title + ‘/‘ + resource title

**Comment by gvidon** [comment]
@pwalsh do you mean file name as resource title? There are no other text properties in resource JSON, except for `.description` https://www.dropbox.com/s/nq1lsk436ldrngn/%D0%A1%D0%BA%D1%80%D0%B8%D0%BD%D1%88%D0%BE%D1%82%202015-04-17%2001.24.33.png?dl=0

In `/resource_show` API end point response there are no text properties too https://www.dropbox.com/s/kmhesryt7zltd7l/%D0%A1%D0%BA%D1%80%D0%B8%D0%BD%D1%88%D0%BE%D1%82%202015-04-17%2001.26.50.png?dl=0

**Comment by rufuspollock** [comment]
What we mean is to take the title from the parent Dataset (cf #6) and concatenate that with the description for the resource. I have to say I'm not sure about this one and we could leave it for now esp if we do #6
