### ISSUE TITLE
Additional fields on entries in datafiles

### ISSUE THREAD

**Issue by pwalsh** [gvidon/uk-expenditure#4]
Could each entry in datafiles also have the following properties:
- format
- encoding

If these are not found for a given entry, they can be set to NULL

**Comment by gvidon** [comment]
@pwalsh I can't find encoding neither in `.resources` section of data set https://www.dropbox.com/s/ipdsz9tvo1t81kd/%D0%A1%D0%BA%D1%80%D0%B8%D0%BD%D1%88%D0%BE%D1%82%202015-04-17%2001.45.35.png?dl=0 nor in `resource_show` API end point https://www.dropbox.com/s/7ygkerwwvkd5xxf/%D0%A1%D0%BA%D1%80%D0%B8%D0%BD%D1%88%D0%BE%D1%82%202015-04-17%2001.46.29.png?dl=0

**Comment by pwalsh** [comment]
Ok, no problem. Thanks for adding format.
