### ISSUE TITLE
Problem in publishers homepage field

### ISSUE THREAD

**Issue by pwalsh** [gvidon/uk-expenditure#5]
The homepage field of publishers seems to have either NULL, or, a link to a page related to the the body on the What Do They Know website. This is not correct. is there another field available that may contain the correct url to the home page?

**Comment by gvidon** [comment]
@pwalsh there there is just one field with URL in API — `.foi-web` https://www.dropbox.com/s/ri8lp9uks7o0wa5/%D0%A1%D0%BA%D1%80%D0%B8%D0%BD%D1%88%D0%BE%D1%82%202015-04-17%2001.48.38.png?dl=0

**Comment by rufuspollock** [comment]
@gvidon i don't think we want foi-web. I think we want this kind of url http://data.gov.uk/publisher/cabinet-office (i.e. the publisher home page url on data.gov.uk) (and where that is not appropriate leave blank).

**Comment by gvidon** [comment]
@rgrp there is already this kind of URL in collected data https://github.com/gvidon/uk-expenditure/blob/master/data/publishers.csv https://www.dropbox.com/s/k7kcgqtyhlqg25p/%D0%A1%D0%BA%D1%80%D0%B8%D0%BD%D1%88%D0%BE%D1%82%202015-04-19%2016.52.23.png?dl=0 but it is called `homepage-for-data`.

Should I swap `homepage` and `homepage-for-data` fields?

**Comment by rufuspollock** [comment]
Yes, please just swap in homepage-for-data into homepage field and we can then drop the old homepage data.
