### ISSUE TITLE
Is it possible to extract the "source page" for each datafile?

### ISSUE THREAD

**Issue by pwalsh** [gvidon/uk-expenditure#6]
Meaning, the page on the official website of the government body that hosts a link to the datafile.

**Comment by gvidon** [comment]
@pwalsh from this example http://data.gov.uk/dataset/vts-december-spend-over-250/resource/701850b5-74d1-4522-80e0-254f6b419a39 is URL what you need https://www.dropbox.com/s/b94579tdda1366c/%D0%A1%D0%BA%D1%80%D0%B8%D0%BD%D1%88%D0%BE%D1%82%202015-04-17%2002.05.35.png?dl=0 ?

**Comment by gvidon** [comment]
Probably not, as it is the URL of file itself.

**Comment by rufuspollock** [comment]
What we want is the "dataset" page on data.gov.uk that we got the resources from e.g. this would be homepage http://data.gov.uk/dataset/financial-transactions-data-fco for the data files listed on that page.

this is api for that dataset http://data.gov.uk/api/rest/dataset/financial-transactions-data-fco and you are probably then grabbing the resource list from it.

**Comment by rufuspollock** [comment]
Note I think maybe we want a "source" table (csv file) which we can point to from the data files page. However, for now let's do the simplest thing and either not do this at all or just add the source-page heading to the csv file for data files.
