### ISSUE TITLE
Store results data in this repo

### ISSUE THREAD

**Issue by rufuspollock** [gvidon/uk-expenditure#8]
Merge spd-data-uk-all with this repo: https://github.com/okfn/spd-data-uk-all/tree/ministerial-dpts/data
- [x] Merge across scripts (put everything in `/scripts/`)
  - How does this connect with spd-admin (do we want to merge spd-admin stuff in here too - probably (?))
- [x] Merge across README
  - What data is in this repo (Data Package like)
  - Extensive section on scripts

---
- [x] Merge results data files in there
  - [x] _Think about removing runs ... (maybe just assume current data is from latest run in runs.csv) - maybe add commit rev number to runs ?_ - DON'T DO NOW
- [x] Merge source data files (publishers, sources etc)
  - [x] publishers (use the one here - discard spd)
  - [x] sources => datafiles.csv

**Comment by pwalsh** [comment]
This work was done by @danfowler a while ago.
